package com.today36524.schoolsoa;

      import com.isuwang.dapeng.core.*;
      import com.isuwang.org.apache.thrift.*;
      import com.isuwang.dapeng.remoting.BaseCommonServiceClient;
      import java.util.concurrent.CompletableFuture;
      import java.util.concurrent.Future;
      import com.today36524.schoolsoa.SchoolServiceCodec.*;

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      **/
      public class SchoolServiceClient extends BaseCommonServiceClient{

      public SchoolServiceClient() {
        super("com.today36524.schoolsoa.service.SchoolService", "1.0.0");
      }

      @Override
      protected boolean isSoaTransactionalProcess(){
        return false;
      }

      
       /**
       * 

    query the school name

       **/
          
              public String findSchoolNameById(String id) throws SoaException{
                initContext("findSchoolNameById");

          try {
             findSchoolNameById_args findSchoolNameById_args = new findSchoolNameById_args();
          findSchoolNameById_args.setId(id);
            

          findSchoolNameById_result response = sendBase(findSchoolNameById_args, new FindSchoolNameById_argsSerializer(), new FindSchoolNameById_resultSerializer());

             
                  
                        return response.getSuccess();
                      
                
          }catch (SoaException e){
              throw e;
          } catch (TException e){
              throw new SoaException(e);
          }finally {
            destoryContext();
          }
          }
            
        
       /**
       * 
       **/
          
              public com.today36524.schoolsoa.bean.School findSchoolById(String id) throws SoaException{
                initContext("findSchoolById");

          try {
             findSchoolById_args findSchoolById_args = new findSchoolById_args();
          findSchoolById_args.setId(id);
            

          findSchoolById_result response = sendBase(findSchoolById_args, new FindSchoolById_argsSerializer(), new FindSchoolById_resultSerializer());

             
                  
                        return response.getSuccess();
                      
                
          }catch (SoaException e){
              throw e;
          } catch (TException e){
              throw new SoaException(e);
          }finally {
            destoryContext();
          }
          }
            
        
       /**
       * 
       **/
          
              public java.util.List<com.today36524.schoolsoa.bean.School> findAllSchool() throws SoaException{
                initContext("findAllSchool");

          try {
             findAllSchool_args findAllSchool_args = new findAllSchool_args();
          

          findAllSchool_result response = sendBase(findAllSchool_args, new FindAllSchool_argsSerializer(), new FindAllSchool_resultSerializer());

             
                  
                        return response.getSuccess();
                      
                
          }catch (SoaException e){
              throw e;
          } catch (TException e){
              throw new SoaException(e);
          }finally {
            destoryContext();
          }
          }
            
        

      /**
      * getServiceMetadata
      **/
      public String getServiceMetadata() throws SoaException {
        initContext("getServiceMetadata");
        try {
          getServiceMetadata_args getServiceMetadata_args = new getServiceMetadata_args();
          getServiceMetadata_result response = sendBase(getServiceMetadata_args, new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer());
          return response.getSuccess();
        }catch (SoaException e){
          throw e;
        } catch (TException e){
          throw new SoaException(e);
        } finally {
          destoryContext();
        }
      }

      }
    