
        package com.today36524.schoolsoa.service;

        import com.isuwang.dapeng.core.Processor;
        import com.isuwang.dapeng.core.Service;
        import com.isuwang.dapeng.core.SoaGlobalTransactional;

        import java.util.concurrent.Future;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

  School service,to query information of schools

        **/
        @Service(name="com.today36524.schoolsoa.service.SchoolService",version = "1.0.0")
        @Processor(className = "com.today36524.schoolsoa.SchoolServiceCodec$Processor")
        public interface SchoolService {
        
            /**
            * 

    query the school name

            **/
            
            
               String findSchoolNameById( String id) throws com.isuwang.dapeng.core.SoaException;
              
          
            /**
            * 
            **/
            
            
               com.today36524.schoolsoa.bean.School findSchoolById( String id) throws com.isuwang.dapeng.core.SoaException;
              
          
            /**
            * 
            **/
            
            
               java.util.List<com.today36524.schoolsoa.bean.School> findAllSchool() throws com.isuwang.dapeng.core.SoaException;
              
          
        }
        